# Generated by Django 5.1.3 on 2025-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='series',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
