# Generated by Django 5.1.3 on 2025-02-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0006_entreno_numero_ejercicios_alter_entreno_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreno',
            name='ejercicios',
        ),
        migrations.AlterField(
            model_name='ejercicio_realizado',
            name='entreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='gymApp.entreno'),
        ),
    ]
