# Generated by Django 5.1.3 on 2025-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0008_entreno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio_realizado',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
