# Generated by Django 5.1.3 on 2025-02-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0010_ejercicio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='usuario',
        ),
    ]
